const PLAYER_MOVEMENTS={
    x:300,
    y:330,
};
const SHAPE_DELAY=1500;

const TRIANGULO= "triangulo";
const CUADRADO= "cuadrado";
const ROMBO= "rombo";
const BOMBA="bomba";
const SHAPES=[TRIANGULO, CUADRADO, ROMBO, BOMBA];
const POINTS_PERCENTAGE = "value";
const POINTS_PERCENTAGE_VALUE_START = 1;


export {PLAYER_MOVEMENTS,SHAPE_DELAY, SHAPES, TRIANGULO, CUADRADO, ROMBO, BOMBA, POINTS_PERCENTAGE, POINTS_PERCENTAGE_VALUE_START,};